project:
  type: website
  output-dir: docs

website:
  title: "Hector Zumbado-Ulate, PhD"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - publications.qmd
      - projects.qmd

format:
  html:
    theme: zephyr
    mainfont: arial
    fontsize: 1.2rem
    css: styles.css
    toc: true
